# CompletableFuture

자바 8에 나온 비동기 기술인 `CompletableFuture`에 대해 알아보자.



개선된 `Future`로써, 리스트의 모든 값이 완료될 때까지 기다릴지, 하나의 값만 완료되길 기다릴지 등 선택하는 것과 람다표현식, 파이프라이닝도 모두 활용하기 좋다.

테스트 코드를 수행해보자.

```java
@Test
void completableTest() throws InterruptedException {
  CompletableFuture.runAsync(() -> log.info("runAsync"));
  log.info("exit");

  ForkJoinPool.commonPool().shutdown();
  ForkJoinPool.commonPool().awaitTermination(3, TimeUnit.SECONDS);
}
```

(밑은 중요하지 않다.)

결과를 보자.

```java
[main] INFO com.async.hello.CompletableFutureTest - exit
[ForkJoinPool.commonPool-worker-3] INFO com.async.hello.CompletableFutureTest - runAsync
```

순서가 바뀌어서 실행된 것을 볼 수 있는데, 물론 빠르게 진행되다보니 순서가 정상일 수도 있다.



CompletableFuture의 중요한 특징 중 하나는 `CompletableStage` 라는 인터페이스(자바 8)를 상속받고 있다는 점이다. 이 상속으로 인해, 이 CompletableFuture의 결과에 이어서 다른 메서드도 실행시킬 수 있다.

다음과 같이 코드를 이어서 진행시킬 경우.

```java
@Test
void completableTest() throws InterruptedException {
  CompletableFuture.runAsync(() -> log.info("runAsync"))
    .thenRun(() -> log.info("thenRun"))
    .thenRun(() -> log.info("thenRun2"));
  log.info("exit");

  ForkJoinPool.commonPool().shutdown();
  ForkJoinPool.commonPool().awaitTermination(3, TimeUnit.SECONDS);
}
```

해당 스레드(계속 같은)에서 작업을 이어서 진행한다. `runAsync` 는 받은 결과가 없어서 거기에 작업을 할 수 없다. 받은 결과로 작업을 이어하고 싶은 경우, `supplyAsync`를 이용하면 된다. 다양한 인터페이스를 통해 쓰는 방법을 보자.

```java
@Test
void completableTest() throws InterruptedException {
  CompletableFuture.supplyAsync(() -> {
    log.info("supplyAsync");
    return 1;
  }).thenApply(s -> {
    log.info("thenApply : {}", s);
    return s + 1;
  }).thenAccept(s -> log.info("thenAccept : {}", s));

  log.info("exit");

  ForkJoinPool.commonPool().shutdown();
  ForkJoinPool.commonPool().awaitTermination(3, TimeUnit.SECONDS);
}
```

이렇게 보면 앞으로 만들 코드가 어떻게 될지 그래도 좀 알 수 있다.



이렇게 체이닝이 될 수 있는 이유는 우리가 return 으로 값을 반환했을 때, 알아서 그걸 `ComputableFuture`로  감싸서 다음 작업을 진행하기 때문이다. 그리고 사용할 때에는 그 안에 있는 값을 꺼내서 사용하게 된다. 근데 외부에서 이용해서 혹시 반환을 우리가 `CompletableFuture`로 감싼 상태로 반환해야 하는 경우도 있다. 이런 경우 `thenCompose`라는 메서드도 지원하니 사용할 수 있다.



#### 예외 핸들링

모든 비동기 작업은 런타임 예외가 발생할 수 있다. 예외가 발생했을 경우 정상적인 루틴을 타고 가면 안된다. 처리하는 방식은 2가지가 있는데, 예외를 계속 그냥 전달하거나 의미있는 값으로 변환해서 다음으로 넘길 수 있다.

만약 어디서든지 예외가 발생했을 때 변환해서 이어 넘기고 싶다면 `exceptionally`를 사용할 수 있다. 항상 콜백에 예외까지 쌍으로 넣어서 사용할 필요가 없다.



#### 만약 쓰레드를 바꿔도 상관없다면..

굳이 쓰레드를 이어서 사용할 필요가 없고 좀 더 자원을 효과적으로 사용하고 싶을 수 있다. 이런 경우 `thenApply` 같은 메서드 대신 뒤에 `Async`가 붙은 `thenApplyAsync`를 사용할 수 있다. 대신 이 경우 `executor` 설정을 별도로 해주어야 한다.

```java
@Test
void completableAsyncTest() throws InterruptedException {
  ExecutorService es = Executors.newFixedThreadPool(10);
  CompletableFuture.supplyAsync(() -> {
    log.info("supplyAsync");
    return 1;}, es)
    .thenApplyAsync(s -> {
      log.info("thenApply : {}", s);
      return s + 1;}, es)
    .exceptionally(e -> 10)
    .thenAcceptAsync(s -> log.info("thenAccept : {}", s), es);

  log.info("exit");

  ForkJoinPool.commonPool().shutdown();
  ForkJoinPool.commonPool().awaitTermination(3, TimeUnit.SECONDS);
}
```

이런 식으로 쓰레드 풀을 할당해준다면, 다음과 같이 다른 쓰레드를 사용하여 진행하는 결과를 얻을 수 있다.

```
[pool-1-thread-1] INFO com.async.hello.CompletableFutureTest - supplyAsync
[main] INFO com.async.hello.CompletableFutureTest - exit
[pool-1-thread-2] INFO com.async.hello.CompletableFutureTest - thenApply : 1
[pool-1-thread-3] INFO com.async.hello.CompletableFutureTest - thenAccept : 2
```